books = [
    'John',
    'Colossians',
    'Galatians',
    'Mark',
    'Philippians',
    'Ephesians',
    'Matthew',
    'James',
    'Jude',
    'Philemon',
    'Romans',
    'Revelation',
    '1 Corinthians',
    '2 Corinthians',
    'Luke',
    'Acts',
    '1 Thessalonians',
    '2 Thessalonians',
    '1 Timothy',
    '2 Timothy',
    'Hebrews',
    'Titus',
    '1 John',
    '2 John',
    '3 John',
    '1 Peter',
    '2 Peter'
]
